apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: rw
  name: resource-watch
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: resource-watch
  minReplicas: 4
  maxReplicas: 8
  targetCPUUtilizationPercentage: 50
