apiVersion: v1
kind: Service
metadata:
  namespace: rw
  labels:
    name: resource-watch
  name: resource-watch
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    name: resource-watch
