version: "3.9"

services:
  postgres_db:
    image: postgres:17-alpine
    restart: always
    network_mode: host
    environment:
      POSTGRES_USER: puser
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: policy_development
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local