apiVersion: v1
kind: Service
metadata:
  namespace: rw
  labels:
    name: resource-watch-preproduction
  name: resource-watch-preproduction
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    name: resource-watch-preproduction
