---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.24.1
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    # Folder weaviate_data needs to be created manually before docker compose up
    - ./weaviate_data:/home/robert/data/weaviate_ps_chatbot
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 50
      DISK_USE_READONLY_PERCENTAGE: 0
      DISK_USE_WARNING_PERCENTAGE: 0
      #AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      AUTHENTICATION_APIKEY_ENABLED: 'true'
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: 'bC80K2dPTEV0N2tkaXdLdV9BYU4wNVJkeFRIelRiSUJoRHlsUGNHWHkzTkNlRjVkSlh1UUJYbFA3ZXBrPV92MjAw'
      AUTHENTICATION_APIKEY_USERS: 'bruno.galdos'
      DEFAULT_VECTORIZER_MODULE: text2vec-openai
      ENABLE_MODULES: ' text2vec-openai'
      OPENAI_APIKEY: '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'
      CLUSTER_HOSTNAME: 'node1'
      #PERSISTENCE_DATA_PATH: '/home/robert/data/weaviate_ps_chatbot'
volumes:
  weaviate_data:
